### Download dataset

In [2]:
import kagglehub
from pathlib import Path

path = Path(kagglehub.dataset_download("irkaal/foodcom-recipes-and-reviews"))
print(path)
for f in path.iterdir():
    print(f.name, f"{f.stat().st_size / 1e6:.1f} MB")

Downloading to /Users/nico/.cache/kagglehub/datasets/irkaal/foodcom-recipes-and-reviews/2.archive...

100%|██████████| 723M/723M [01:00<00:00, 12.6MB/s]

Extracting files...

/Users/nico/.cache/kagglehub/datasets/irkaal/foodcom-recipes-and-reviews/versions/2
reviews.csv 496.1 MB
recipes.csv 704.2 MB
recipes.parquet 178.7 MB
reviews.parquet 173.8 MB

### Load into pandas and explore dataset

In [7]:
import pandas as pd

recipes = pd.read_parquet(path / "recipes.parquet")
reviews = pd.read_parquet(path / "reviews.parquet")

In [8]:
recipes.head()

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,38.0,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,PT24H,PT45M,PT24H45M,1999-08-09 21:46:00+00:00,Make and share this Low-Fat Berry Blue Frozen ...,[https://img.sndimg.com/food/image/upload/w_55...,...,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"[Toss 2 cups berries with sugar., Let stand fo..."
1,39.0,Biryani,1567,elly9812,PT25M,PT4H,PT4H25M,1999-08-29 13:12:00+00:00,Make and share this Biryani recipe from Food.com.,[https://img.sndimg.com/food/image/upload/w_55...,...,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,[Soak saffron in warm milk for 5 minutes and p...
2,40.0,Best Lemonade,1566,Stephen Little,PT5M,PT30M,PT35M,1999-09-05 19:52:00+00:00,This is from one of my first Good House Keepi...,[https://img.sndimg.com/food/image/upload/w_55...,...,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"[Into a 1 quart Jar with tight fitting lid, pu..."
3,41.0,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,PT20M,PT24H,PT24H20M,1999-09-03 14:54:00+00:00,This dish is best prepared a day in advance to...,[https://img.sndimg.com/food/image/upload/w_55...,...,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"[Drain the tofu, carefully squeezing out exces..."
4,42.0,Cabbage Soup,1538,Duckie067,PT30M,PT20M,PT50M,1999-09-19 06:19:00+00:00,Make and share this Cabbage Soup recipe from F...,[https://img.sndimg.com/food/image/upload/w_55...,...,0.1,0.0,959.3,25.1,4.8,17.7,4.3,4.0,NaN,"[Mix everything together and bring to a boil.,..."

In [9]:
recipes.info()

<class 'pandas.DataFrame'>
RangeIndex: 522517 entries, 0 to 522516
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   RecipeId                    522517 non-null  float64
 1   Name                        522517 non-null  str
 2   AuthorId                    522517 non-null  int32
 3   AuthorName                  522517 non-null  str
 4   CookTime                    439972 non-null  str
 5   PrepTime                    522517 non-null  str
 6   TotalTime                   522517 non-null  str
 7   DatePublished               522517 non-null  datetime64[us, UTC]
 8   Description                 522512 non-null  str
 9   Images                      522516 non-null  object
 10  RecipeCategory              521766 non-null  str
 11  Keywords                    522517 non-null  object
 12  RecipeIngredientQuantities  522517 non-null  object
 13  RecipeIngredientParts       522517 non-null  object
 14  AggregatedRating            269294 non-null  float64
 15  ReviewCount                 275028 non-null  float64
 16  Calories                    522517 non-null  float64
 17  FatContent                  522517 non-null  float64
 18  SaturatedFatContent         522517 non-null  float64
 19  CholesterolContent          522517 non-null  float64
 20  SodiumContent               522517 non-null  float64
 21  CarbohydrateContent         522517 non-null  float64
 22  FiberContent                522517 non-null  float64
 23  SugarContent                522517 non-null  float64
 24  ProteinContent              522517 non-null  float64
 25  RecipeServings              339606 non-null  float64
 26  RecipeYield                 174446 non-null  str
 27  RecipeInstructions          522517 non-null  object
dtypes: datetime64[us, UTC](1), float64(13), int32(1), object(5), str(8)
memory usage: 234.4+ MB

In [10]:
reviews.head()

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,5,better than any you can get at a restaurant!,2000-01-25 21:44:00+00:00,2000-01-25 21:44:00+00:00
1,7,4384,1634,Bill Hilbrich,4,"I cut back on the mayo, and made up the differ...",2001-10-17 16:49:59+00:00,2001-10-17 16:49:59+00:00
2,9,4523,2046,Gay Gilmore ckpt,2,i think i did something wrong because i could ...,2000-02-25 09:00:00+00:00,2000-02-25 09:00:00+00:00
3,13,7435,1773,Malarkey Test,5,easily the best i have ever had. juicy flavor...,2000-03-13 21:15:00+00:00,2000-03-13 21:15:00+00:00
4,14,44,2085,Tony Small,5,An excellent dish.,2000-03-28 12:51:00+00:00,2000-03-28 12:51:00+00:00